apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-nodeport
  namespace: airflow
spec:
  type: NodePort
  selector:
    component: webserver
    release: airflow
    tier: airflow
  ports:
    - name: airflow-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080  
  externalTrafficPolicy: Cluster
